console.log("EJERCICIO 1")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")
console.log("Girar a la izquierda")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")

console.log("EJERCICIO 2")
console.log("Avanzar 1 casillero")
console.log("Llenar hoyo de tierra (x1)")
console.log("Avanzar 1 casillero")
console.log("Avanzar 1 casillero")
console.log("Avanzar 1 casillero")
console.log("Llenar hoyo de tierra (x1)")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")
console.log("Avanzar 1 casillero")

console.log("EJERCICIO 3")
console.log("Girar a la izquierda")
console.log("Avanzar 1 casillero")
console.log("Girar a la derecha")
console.log("Avanzar 1 casillero")
console.log("Avanzar 1 casillero")
console.log("Girar a la derecha")
console.log("Avanzar 1 casillero")
console.log("Quitar pila de tierra (x1)")