console.log("PREPARAR UN TORTA")
console.log("")
console.log("1- Salir de casa y dirigirme al supermercado a realizar las compras")
console.log("")
console.log("2- Comprar harina, azucar, leche, esencia de vainilla, huevos y polvo de hornear (levadura)")
console.log("")
console.log("3- Pagar y regresar a casa")
console.log("")
console.log("4- Una vez en casa dirigirme a la cocina y preparar los utensillos a utilizar")
console.log("")
console.log("5- Comenzar a preparar la torta siguiendo los pasos especificados en la receta")
console.log("")
console.log("6- Terminada la mezcla meter a hornear")
console.log("")
console.log("7- Esperar el tiempo especificado y retirar del horno")
console.log("")
console.log("8- Poner a enfriar a temperatura ambiente o en algun sitio frio (heladera)")
console.log("")
console.log("9- Servir la torta lista para consumo")
console.log("")
console.log("10- Disfrutar, solo o en compania!!")
console.log("")